"""Add departure and arrival places to Schedule model

Revision ID: 72b16692b464
Revises: c065919e5122
Create Date: 2023-12-03 22:01:24.427998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72b16692b464'
down_revision = 'c065919e5122'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles')
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('departure_place', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('arrival_place', sa.String(length=255), nullable=False))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('role_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    

    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.drop_column('arrival_place')
        batch_op.drop_column('departure_place')

    # ### end Alembic commands ###
